# Site settings
title: Deadzone
storelink: http://www.manticgames.com/mantic-shop/deadzone/product/deadzone-the-sci-fi-skirmish-game.html
email: info@manticgames.com
description: 
baseurl: "/dz/"  # the subpath of your site, e.g. /blog/
url: "http://mattl.git.io" # the base hostname & protocol for your site
twitter_username: manticgames
github_username:  

# Build settings
markdown: kramdown
